# Generated by Django 3.1.5 on 2021-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student_name',
            field=models.CharField(default=2020, max_length=255),
            preserve_default=False,
        ),
    ]
